sudo: required
dist: trusty
language: ruby
rvm:
  - 1.9.3
  - 2.0
  - 2.1
  - 2.2
  - 2.3
  - jruby-9.1.5.0
before_install:
  - gem update --system
  - gem --version
  - gem update bundler
bundler_args: "--binstubs --path=vendor --without=guard"
before_script:
  - cp -vf ./spec/support/test_client.yml.example ./spec/support/test_client.yml
  - echo 'Test client config:'
  - cat ./spec/support/test_client.yml
  - sudo ./tools/travis-ci/riak-install
  - sudo ./tools/devrel/riak-cluster-config "$(which riak-admin)" 8098 false false
script:
  - bundle exec rubocop lib spec
  - bundle exec rake spec spec:integration
notifications:
  slack:
    secure: nryEZNlLs0xpMJcrmTRzJIaFdfHWigsD4i9zEI8SgDdHqEgJ52/UfCifWHC7N4UckpRkmMUc8yt/Y4YS7G4Gu4yx4qXNIL33VmuudUe2YEVv+oVnG9oHVPkHDvOkRSLlWyAIqd4uXbLzghYBrHigoinfCcmjjRq5HNocRrvnwdE=
